python -m train_model \
    --train ./data/EN-English/en_train.conll \
    --dev ./data/EN-English/en_dev.conll \
    --gazetteer ../gazetteer_demo/en \
    --out_dir ./output/ \
    --model_name ner_multiconer_en \
    --gpus 1 \
    --epochs 20 \
    --encoder_model xlm-roberta-large \
    --batch_size 32 \
    --lr 0.00002 \
    --iob_tagging wnut